title: Being the lazy me
theme: minima
author: Sanskriti
email: sanskritiagrawal2907@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just another blog created to give a shot at trying to learn github. Go ahead, explore!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Sanskritiag # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
